name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to GitHub Docker Registry
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: docker login docker.pkg.github.com -u antoniomika -p $GITHUB_TOKEN
    - name: Build the Docker image
      run: docker build -t docker.pkg.github.com/antoniomika/bonjourproxy/bonjourproxy:latest .
    - name: Push the Docker image
      run: docker push docker.pkg.github.com/antoniomika/bonjourproxy/bonjourproxy:latest