name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to GitHub Docker Registry
      env:
        DOCKER_USERNAME: ${{ secrets.GITHUB_DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_DOCKER_PASSWORD }}
      run: echo $DOCKER_PASSWORD | docker login docker.pkg.github.com -u $DOCKER_USERNAME --password-stdin
    - name: Build the Docker image
      run: docker build -t docker.pkg.github.com/antoniomika/bonjourproxy/bonjourproxy:latest .
    - name: Push the Docker image
      run: docker push docker.pkg.github.com/antoniomika/bonjourproxy/bonjourproxy:latest